export enum MATCH_STATE {
    MATCHED = 1,
    CALL_INITIATED_BY_RECRUITER = 2,
    CALL_INITIATED_BY_CANDIDATE = 3,
    CALL_DECLINED_BY_RECRUITER = 4,
    CALL_DECLINED_BY_CANDIDATE = 5,
    CALL_ACCEPTED_BY_RECRUITER = 6,
    CALL_ACCEPTED_BY_CANDIDATE = 7,
    CALL_STARTED = 8,
    PROPOSAL_DECLINED_BY_RECRUITER = 9,
    PROPOSAL_DECLINED_BY_CANDIDATE = 10,
    PROPOSAL_ACCEPTED_BY_RECRUITER = 11,
    PROPOSAL_ACCEPTED_BY_CANDIDATE = 12,
    PROPOSAL_ACCEPTED_BY_BOTH = 13,
    CALL_ENDED = 14
}