export enum MATCH_STATE {
    MATCHED = 1,
    RECRUITER_JOINED_CALL = 2,
    CANDIDATE_JOINED_CALL = 3,
    CALL_ENDED = 4,
    PROPOSAL_ACCEPTED_BY_RECRUITER = 5,
    PROPOSAL_ACCEPTED_BY_CANDIDATE = 6
}

export enum SEARCH_TYPE {
    RECRUITER = 1,
    CANDIDATE = 2
}

export enum SEARCH_CHANGE_TYPE {
    NO_CHANGE = 0,
    NON_CRITICAL_CHANGE = 1,
    CRITICAL_CHANGE = 2
}