export enum MATCH_STATE {
    MATCHED = 1,
    CALL_INITIATED_BY_RECRUITER = 2,
    CALL_INITIATED_BY_CANDIDATE = 3,
    CALL_STARTED = 4,
    BLOCK_BEFORE_CALL_START_BY_RECRUITER = 5,
    BLOCK_BEFORE_CALL_START_BY_CANDIDATE = 6,
    BLOCK_AFTER_CALL_END_BY_RECRUITER = 7,
    BLOCK_AFTER_CALL_END_BY_CANDIDATE = 8,
    PROPOSAL_ACCEPTED_BY_RECRUITER = 9,
    PROPOSAL_ACCEPTED_BY_CANDIDATE = 10,
    PROPOSAL_REJECTED_BY_RECRUITER = 11,
    PROPOSAL_REJECTED_BY_CANDIDATE = 12,
    PROPOSAL_ACCEPTED_BY_BOTH = 13
}